"""
devOps node — trigger deployment for locally modified files.

Responsibilities (LOCAL-FIRST):
  1. Capture any artifact diffs generated by earlier agents.
  2. POST to the deployment dashboard to trigger downstream CI/CD.

No git operations are performed — changes are already on the local filesystem.
"""

from __future__ import annotations

import json
import os
import urllib.error
import urllib.request

from src.nodes._utils import base_state
from src.state import AgentState


def dev_ops_node(state: AgentState) -> AgentState:
    print("Agent devOps is working.")

    if not state.get("test_passed", False):
        return base_state(
            state,
            "[devOps] Deployment skipped — tests did not pass.",
            "devOps",
        )

    repo_path = state.get("repo_path", "")
    if not repo_path:
        return base_state(
            state,
            "[devOps] No repo_path in state — skipped.",
            "devOps",
        )

    project_path: str = state.get("project_path", repo_path)
    artifacts: list[str] = list(state.get("artifacts") or [])

    # Trigger deployment dashboard (fire-and-forget; errors are non-fatal)
    deploy_status = "DEPLOY_DASHBOARD_URL not set — skipped"
    dashboard_url = os.environ.get("DEPLOY_DASHBOARD_URL", "")
    if dashboard_url:
        payload = json.dumps(
            {
                "project": project_path,
                "status": "ready",
                "triggered_by": "AgentHub",
            }
        ).encode("utf-8")
        req = urllib.request.Request(
            dashboard_url,
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:  # noqa: S310
                body = resp.read().decode("utf-8", errors="replace")
            deploy_status = f"HTTP {resp.status} — {body[:200]}"
        except urllib.error.URLError as exc:
            deploy_status = f"ERROR: {exc}"

    return {
        **base_state(
            state,
            f"[devOps] Local changes ready | deploy notification: {deploy_status}",
            "devOps",
        ),
        "artifacts": artifacts,
    }
