"""
devops_manual_guide node — generates docs/deployment_guide.md.

Activated on MANUAL_DEPLOY_REQUESTED (user chose Manual at the tech_lead_gate).
Writes a concrete, copy-pasteable guide derived from current task context.
"""

from __future__ import annotations

from pathlib import Path

from src.nodes._utils import base_state
from src.state import AgentState


def devops_manual_guide_node(state: AgentState) -> AgentState:
    print("Agent devOps is generating the manual deployment guide.")

    repo_path = state.get("repo_path", "")
    github_url = state.get("github_url", "<repo-url>")
    task = state.get("task_description", "<task>")

    guide_lines = [
        "# Deployment Guide",
        "",
        f"**Task:** {task}",
        f"**Repository:** {github_url}",
        "",
        "## Prerequisites",
        "",
        "| Tool | Version | Install |",
        "|---|---|---|",
        "| AWS CLI | ≥ 2.13 | `winget install Amazon.AWSCLI` / `brew install awscli` |",
        "| Node.js | 20.x LTS | https://nodejs.org |",
        "| AWS CDK | ≥ 2.x | `npm install -g aws-cdk` |",
        "| TypeScript | ≥ 5.x | `npm install -g typescript` |",
        "",
        "## Pre-Deployment Checklist",
        "",
        "- [ ] Authenticated to the correct AWS account: `aws sts get-caller-identity`",
        "- [ ] CDK synth passes: `npx cdk synth --context env=prod`",
        "- [ ] Change set reviewed: `npx cdk diff --context env=prod`",
        "",
        "## Step-by-Step Deployment",
        "",
        "```bash",
        "# 1. Install dependencies",
        "npm ci",
        "",
        "# 2. Build TypeScript",
        "npm run build",
        "",
        "# 3. Review what will change (read every [+] and [-] line)",
        "npx cdk diff --context env=prod",
        "",
        "# 4. Deploy — pauses on any broadening security change",
        "npx cdk deploy --all --context env=prod --require-approval broadening",
        "```",
        "",
        "## Verification",
        "",
        "```bash",
        "# CloudWatch alarms must all be OK",
        "aws cloudwatch describe-alarms --state-value OK "
        "--query 'MetricAlarms[*].[AlarmName,StateValue]' --output table",
        "",
        "# DLQ must be empty",
        'aws sqs get-queue-attributes --queue-url "$DLQ_URL" '
        "--attribute-names ApproximateNumberOfMessages",
        "",
        "# Health endpoint smoke test",
        'for i in $(seq 1 10); do curl -s -o /dev/null -w "Check $i: %{http_code}\\n" '
        '"$API_ENDPOINT/health"; done',
        "```",
        "",
        "## Rollback Plan",
        "",
        "```bash",
        "# Option A: Lambda alias rollback (< 60 seconds)",
        "aws lambda update-alias --function-name <function> --name live "
        "--function-version <prev-version> --routing-config AdditionalVersionWeights={}",
        "",
        "# Option B: CloudFormation stack rollback",
        "aws cloudformation rollback-stack --stack-name <stack-name>",
        "",
        "# Option C: Git revert + redeploy",
        "git revert HEAD --no-edit && git push origin main",
        "```",
        "",
        "---",
        f"Generated by: @devOps — deployment_guide skill  ",
        f"Signal: DEPLOYMENT_GUIDE_READY",
    ]

    guide_content = "\n".join(guide_lines)
    guide_path = "docs/deployment_guide.md"

    if repo_path:
        out = Path(repo_path) / guide_path
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(guide_content, encoding="utf-8")
    else:
        out = Path(guide_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(guide_content, encoding="utf-8")

    return {
        **base_state(
            state,
            f"[devOps] DEPLOYMENT_GUIDE_READY — guide written to {guide_path}",
            "generate_manual_guide",
        ),
        "deployment_guide_path": guide_path,
    }
